Nama = input("Masukkan nama : ")
Umur = input("Masukkan umur : ")
Alamat = input("Masukkan alamat : ")
Jurusan = input("Masukkan jurusan : ")

print("\n---BIODATA---")
print("Nama : " + Nama)
print("Umur : " + Umur)
print("Alamat : " + Alamat)
print("Jurusan : " + Jurusan)
